stages:
  - build

build-pip-package:
  stage: build
  image: python:3.11
  script:
    - cat $PYPIRC > /tmp/.pypirc
    - |
      if [ -n "$CI_COMMIT_TAG" ]; then
        VERSION="$CI_COMMIT_TAG"
      elif [ -n "$CI_JOB_ID" ]; then
        VERSION="$CI_JOB_ID"
      else
        VERSION="0.0.0-dev"
      fi
    - echo "__version__ = \"$VERSION\"" > auto_commit_ai/_version.py
    # - echo "Updated auto_commit_ai/_version.py with version: $VERSION"
    - python -m pip install build
    - python -m build
    - python -m pip install twine
    - python -m twine upload dist/* --config-file /tmp/.pypirc
  only:
    - tags
